/* Service Worker —— 离线缓存
   缓存网页+资源+音频，学生在线打开一次后即可离线做题。
   加新单元后请把 CACHE 版本号 +1（触发更新）。 */
const CACHE = "vce-zhongwen-v41";
const CORE = [
  "./", "./index.html", "./teacher.html", "./login.html", "./manifest.json", "./icon.svg",
  "./assets/icons/icon-192.png", "./assets/icons/icon-512.png",
  "./assets/icons/icon-maskable-512.png", "./assets/icons/apple-touch-icon.png",
  "./assets/style.css", "./assets/catalog.js", "./assets/lesson.js", "./assets/report-config.js", "./assets/auth.js",
  "./assets/fonts/lxgw-kai.woff2",
  // 受保护内容外壳（Y11/Y12 共用这一个页面，正文从 Supabase 拉）。
  // 词卡音频不进 CORE：15 节共 600+ 条，全预缓存会把首次安装拖垮；
  // 它们走 sw 的运行时缓存（音频是 cache-first），学生听过一次即可离线。
  "./units/protected/index.html",
  "./units/kongzi/index.html", "./units/kongzi/words.js",
  "./units/kongzi/audio/reading-article.mp3", "./units/kongzi/audio/reading-dialogue.mp3",
  "./units/kongzi/1.html", "./units/kongzi/2.html", "./units/kongzi/3.html", "./units/kongzi/4.html", "./units/kongzi/5.html", "./units/kongzi/6.html", "./units/kongzi/7.html", "./units/kongzi/8.html",
  "./units/kongzi/audio/retell-story.mp3", "./units/kongzi/audio/intro-confucius.mp3",
  "./units/kongzi/audio/seg1.mp3", "./units/kongzi/audio/seg2.mp3",
  "./units/kongzi/audio/seg3.mp3", "./units/kongzi/audio/seg4.mp3",
  "./units/kongzi/audio/seg5.mp3", "./units/kongzi/audio/seg6.mp3",
  "./units/kongzi/audio/seg7.mp3", "./units/kongzi/audio/seg8.mp3",
  // 诸葛亮课
  "./units/zhuge/index.html", "./units/zhuge/words.js",
  "./units/zhuge/1.html", "./units/zhuge/2.html", "./units/zhuge/3.html", "./units/zhuge/4.html",
  "./units/zhuge/5.html", "./units/zhuge/6.html", "./units/zhuge/7.html", "./units/zhuge/8.html", "./units/zhuge/9.html", "./units/zhuge/10.html", "./units/zhuge/11.html",
  "./units/zhuge/audio/dialogue-full.mp3", "./units/zhuge/audio/reading-narrative.mp3", "./units/zhuge/audio/retell-arrows.mp3", "./units/zhuge/audio/intro-zhuge.mp3",
  "./units/zhuge/audio/beat1.mp3", "./units/zhuge/audio/beat2.mp3", "./units/zhuge/audio/beat3.mp3",
  "./units/zhuge/audio/beat4.mp3", "./units/zhuge/audio/beat5.mp3", "./units/zhuge/audio/beat6.mp3",
  "./units/zhuge/audio/beat7.mp3",
  "./units/zhuge/img/beat1.png", "./units/zhuge/img/beat2.png", "./units/zhuge/img/beat3.png",
  "./units/zhuge/img/beat4.png", "./units/zhuge/img/beat5.png", "./units/zhuge/img/beat6.png",
  "./units/zhuge/img/beat7.png", "./units/zhuge/img/portrait-card.png",
  // 练习一 · 人物介绍
  "./units/renwu-practice/index.html", "./units/renwu-practice/1.html",
  "./units/renwu-practice/2.html", "./units/renwu-practice/3.html",
  "./units/renwu-practice/img/appearance-01.webp", "./units/renwu-practice/img/appearance-02.webp",
  "./units/renwu-practice/img/appearance-03.webp", "./units/renwu-practice/img/appearance-04.webp",
  "./units/renwu-practice/img/appearance-05.webp", "./units/renwu-practice/img/appearance-06.webp",
  "./units/renwu-practice/img/appearance-07.webp", "./units/renwu-practice/img/appearance-08.webp",
  "./units/renwu-practice/img/appearance-09.webp", "./units/renwu-practice/img/appearance-10.webp",
  "./units/renwu-practice/img/appearance-11.webp", "./units/renwu-practice/img/appearance-12.webp",
  "./units/renwu-practice/img/zhuge-example.webp", "./units/renwu-practice/img/kongzi-hero.webp",
  "./units/renwu-practice/img/zhuge-hero.webp",
  // 练习二 · 介绍人物-诸葛亮
  "./units/renwu-zhuge-practice/index.html", "./units/renwu-zhuge-practice/1.html",
  "./units/renwu-zhuge-practice/2.html", "./units/renwu-zhuge-practice/3.html",
  "./units/renwu-zhuge-practice/img/zhuge-hero.webp", "./units/renwu-zhuge-practice/img/zhuge-example.webp",
  "./units/renwu-zhuge-practice/audio/words/纶巾.mp3", "./units/renwu-zhuge-practice/audio/words/羽扇.mp3",
  "./units/renwu-zhuge-practice/audio/words/身材高大.mp3", "./units/renwu-zhuge-practice/audio/words/风度翩翩.mp3",
  "./units/renwu-zhuge-practice/audio/words/面带微笑.mp3", "./units/renwu-zhuge-practice/audio/words/目光坚定.mp3",
  "./units/renwu-zhuge-practice/audio/words/沉着冷静.mp3", "./units/renwu-zhuge-practice/audio/words/不慌不忙.mp3",
  "./units/renwu-zhuge-practice/audio/words/从容不迫.mp3", "./units/renwu-zhuge-practice/audio/words/气定神闲.mp3",
  "./units/renwu-zhuge-practice/audio/words/胸有成竹.mp3", "./units/renwu-zhuge-practice/audio/words/聚精会神.mp3",
  // 其它 · 足部
  "./units/other/foot/index.html",
  "./units/other/foot/audio/下跌.mp3",
  "./units/other/foot/audio/可疑.mp3",
  "./units/other/foot/audio/奔跑.mp3",
  "./units/other/foot/audio/怀疑.mp3",
  "./units/other/foot/audio/条条大路通罗马.mp3",
  "./units/other/foot/audio/疑.mp3",
  "./units/other/foot/audio/疑问.mp3",
  "./units/other/foot/audio/相距.mp3",
  "./units/other/foot/audio/看见.mp3",
  "./units/other/foot/audio/脚趾.mp3",
  "./units/other/foot/audio/见.mp3",
  "./units/other/foot/audio/足.mp3",
  "./units/other/foot/audio/足球.mp3",
  "./units/other/foot/audio/趾.mp3",
  "./units/other/foot/audio/趾甲.mp3",
  "./units/other/foot/audio/跃.mp3",
  "./units/other/foot/audio/跌.mp3",
  "./units/other/foot/audio/跌倒.mp3",
  "./units/other/foot/audio/跌落.mp3",
  "./units/other/foot/audio/跑.mp3",
  "./units/other/foot/audio/跑得飞快.mp3",
  "./units/other/foot/audio/跑步.mp3",
  "./units/other/foot/audio/距.mp3",
  "./units/other/foot/audio/距离.mp3",
  "./units/other/foot/audio/跟.mp3",
  "./units/other/foot/audio/跟上.mp3",
  "./units/other/foot/audio/跟着.mp3",
  "./units/other/foot/audio/跟随.mp3",
  "./units/other/foot/audio/路.mp3",
  "./units/other/foot/audio/路口.mp3",
  "./units/other/foot/audio/跳.mp3",
  "./units/other/foot/audio/跳舞.mp3",
  "./units/other/foot/audio/跳跃.mp3",
  "./units/other/foot/audio/跳高.mp3",
  "./units/other/foot/audio/踢.mp3",
  "./units/other/foot/audio/踢球.mp3",
  "./units/other/foot/audio/踢足球.mp3",
  "./units/other/foot/audio/道路.mp3",
  "./units/other/foot/audio/飞跃.mp3",
  "./units/other/foot/audio/马路.mp3",
  // 其它 · 止部
  "./units/other/stop/index.html",
  "./units/other/stop/audio/一些.mp3",
  "./units/other/stop/audio/不客气.mp3",
  "./units/other/stop/audio/乘.mp3",
  "./units/other/stop/audio/乘客.mp3",
  "./units/other/stop/audio/乘法.mp3",
  "./units/other/stop/audio/乘车.mp3",
  "./units/other/stop/audio/乘风破浪.mp3",
  "./units/other/stop/audio/些.mp3",
  "./units/other/stop/audio/企.mp3",
  "./units/other/stop/audio/企业.mp3",
  "./units/other/stop/audio/企图.mp3",
  "./units/other/stop/audio/企鹅.mp3",
  "./units/other/stop/audio/保卫国家.mp3",
  "./units/other/stop/audio/做客.mp3",
  "./units/other/stop/audio/停止.mp3",
  "./units/other/stop/audio/先.mp3",
  "./units/other/stop/audio/先生.mp3",
  "./units/other/stop/audio/先辈.mp3",
  "./units/other/stop/audio/兴趣.mp3",
  "./units/other/stop/audio/出.mp3",
  "./units/other/stop/audio/出发.mp3",
  "./units/other/stop/audio/出国.mp3",
  "./units/other/stop/audio/出息.mp3",
  "./units/other/stop/audio/出门.mp3",
  "./units/other/stop/audio/前.mp3",
  "./units/other/stop/audio/前方.mp3",
  "./units/other/stop/audio/前面.mp3",
  "./units/other/stop/audio/卫.mp3",
  "./units/other/stop/audio/历.mp3",
  "./units/other/stop/audio/历历在目.mp3",
  "./units/other/stop/audio/历史.mp3",
  "./units/other/stop/audio/发.mp3",
  "./units/other/stop/audio/发作业.mp3",
  "./units/other/stop/audio/发工资.mp3",
  "./units/other/stop/audio/发现.mp3",
  "./units/other/stop/audio/发短信.mp3",
  "./units/other/stop/audio/各.mp3",
  "./units/other/stop/audio/各位同学.mp3",
  "./units/other/stop/audio/各种.mp3",
  "./units/other/stop/audio/各种各样.mp3",
  "./units/other/stop/audio/回复.mp3",
  "./units/other/stop/audio/因此.mp3",
  "./units/other/stop/audio/城市.mp3",
  "./units/other/stop/audio/复.mp3",
  "./units/other/stop/audio/复习.mp3",
  "./units/other/stop/audio/头发.mp3",
  "./units/other/stop/audio/奔.mp3",
  "./units/other/stop/audio/奔跑.mp3",
  "./units/other/stop/audio/客.mp3",
  "./units/other/stop/audio/客人.mp3",
  "./units/other/stop/audio/客厅.mp3",
  "./units/other/stop/audio/市.mp3",
  "./units/other/stop/audio/市长.mp3",
  "./units/other/stop/audio/征.mp3",
  "./units/other/stop/audio/征求意见.mp3",
  "./units/other/stop/audio/散步.mp3",
  "./units/other/stop/audio/有趣.mp3",
  "./units/other/stop/audio/止.mp3",
  "./units/other/stop/audio/正.mp3",
  "./units/other/stop/audio/正在.mp3",
  "./units/other/stop/audio/正方形.mp3",
  "./units/other/stop/audio/正确.mp3",
  "./units/other/stop/audio/正面影响.mp3",
  "./units/other/stop/audio/此.mp3",
  "./units/other/stop/audio/此时此刻.mp3",
  "./units/other/stop/audio/步.mp3",
  "./units/other/stop/audio/步行街.mp3",
  "./units/other/stop/audio/狂奔.mp3",
  "./units/other/stop/audio/登.mp3",
  "./units/other/stop/audio/登场.mp3",
  "./units/other/stop/audio/登山.mp3",
  "./units/other/stop/audio/登机.mp3",
  "./units/other/stop/audio/登记.mp3",
  "./units/other/stop/audio/经历.mp3",
  "./units/other/stop/audio/行人止步.mp3",
  "./units/other/stop/audio/行走.mp3",
  "./units/other/stop/audio/走.mp3",
  "./units/other/stop/audio/走出.mp3",
  "./units/other/stop/audio/走路.mp3",
  "./units/other/stop/audio/赶.mp3",
  "./units/other/stop/audio/赶不上.mp3",
  "./units/other/stop/audio/赶快.mp3",
  "./units/other/stop/audio/赶紧.mp3",
  "./units/other/stop/audio/起.mp3",
  "./units/other/stop/audio/起床.mp3",
  "./units/other/stop/audio/起来.mp3",
  "./units/other/stop/audio/起跑线.mp3",
  "./units/other/stop/audio/超.mp3",
  "./units/other/stop/audio/超市.mp3",
  "./units/other/stop/audio/超越.mp3",
  "./units/other/stop/audio/超车.mp3",
  "./units/other/stop/audio/越.mp3",
  "./units/other/stop/audio/越来越好.mp3",
  "./units/other/stop/audio/越过.mp3",
  "./units/other/stop/audio/趣.mp3",
  "./units/other/stop/audio/跑步.mp3",
  "./units/other/stop/audio/这些.mp3",
  "./units/other/stop/audio/追赶.mp3",
  "./units/other/stop/audio/那些.mp3",
  "./units/other/stop/audio/阻止.mp3",
  "./units/other/stop/audio/集市.mp3",
  "./units/other/stop/audio/飞奔.mp3",
  "./units/other/stop/audio/首先.mp3",

  "./units/geren-ziwo/index.html", "./units/geren-ziwo/words.js",
  "./units/geren-ziwo/1.html", "./units/geren-ziwo/2.html", "./units/geren-ziwo/3.html",
  "./units/geren-ziwo/4.html", "./units/geren-ziwo/5.html", "./units/geren-ziwo/6.html",
  "./units/geren-ziwo/7.html",
  "./units/geren-ziwo/audio/reading-sl.mp3", "./units/geren-ziwo/audio/reading-sla.mp3",
  // 个人情况 · 介绍家庭
  "./units/geren-jiating/index.html", "./units/geren-jiating/words.js",
  "./units/geren-jiating/1.html", "./units/geren-jiating/2.html", "./units/geren-jiating/3.html",
  "./units/geren-jiating/4.html", "./units/geren-jiating/5.html", "./units/geren-jiating/6.html",
  "./units/geren-jiating/7.html",
  "./units/geren-jiating/audio/reading-sl.mp3", "./units/geren-jiating/audio/reading-sla3.mp3",
  "./units/geren-jiating/audio/reading-sla4.mp3"
];

self.addEventListener("install", e => {
  e.waitUntil(
    caches.open(CACHE).then(c => Promise.allSettled(CORE.map(u => c.add(u))))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", e => {
  e.waitUntil(
    caches.keys().then(ks => Promise.all(ks.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", e => {
  const req = e.request;
  if (req.method !== "GET") return;                       // 成绩提交(POST)不拦，直连网络
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;             // 跨域(Supabase/CDN)不缓存，直连

  // 网页/CSS/JS = 网络优先（联网永远最新，离线才用缓存）；音频/字体/图片 = 缓存优先（快+离线）
  const netFirst = req.mode === "navigate" || /\.(html|css|js)$/.test(url.pathname);
  const save = res => { const c = res.clone(); caches.open(CACHE).then(x => x.put(req, c)); return res; };

  if (netFirst) {
    e.respondWith(fetch(req).then(save).catch(() => caches.match(req)));
  } else {
    e.respondWith(caches.match(req).then(hit => hit || fetch(req).then(save)));
  }
});
