/* ============================================================
   孔子课 · 重点词词库（划线词弹卡数据源）
   拼音 py / 中文释义 zh / 英文 en / 读音 audio
   注释可随时改这里；audio 指向 audio/words/<词>.mp3
   ============================================================ */
window.WORDS = {
  "氏":       { py:"shì",              zh:"姓氏；孔子姓孔",              en:"clan / family name (surname)" },
  "丘":       { py:"Qiū",              zh:"孔子的名",                    en:"Qiu (Confucius's given name)" },
  "仲尼":     { py:"Zhòngní",          zh:"孔子的字",                    en:"Zhongni (his courtesy name)" },
  "鲁":       { py:"Lǔ",               zh:"春秋时的鲁国（今山东）",       en:"the State of Lu (today's Shandong)" },
  "陬邑":     { py:"Zōuyì",            zh:"孔子出生的地方",              en:"Zouyi (his birthplace)" },
  "家境":     { py:"jiājìng",          zh:"家里的经济情况",              en:"family's financial situation" },
  "责任":     { py:"zérèn",            zh:"应尽的义务",                  en:"responsibility; duty" },
  "仓库管理": { py:"cāngkù guǎnlǐ",    zh:"看管仓库的工作",              en:"managing a warehouse" },
  "牲畜饲养": { py:"shēngchù sìyǎng",  zh:"喂养牛羊等家畜",              en:"raising / feeding livestock" },
  "据记载":   { py:"jù jìzǎi",         zh:"根据书上的记录",              en:"according to records" },
  "健壮":     { py:"jiànzhuàng",       zh:"强壮有力",                    en:"strong and sturdy" },
  "长人":     { py:"cháng rén",        zh:"“高个子”（当时对孔子的称呼）",  en:"“the tall man” (what people called him)" },
  "贫困":     { py:"pínkùn",           zh:"很穷",                        en:"poor; poverty" },
  "礼乐":     { py:"lǐyuè",            zh:"礼仪和音乐",                  en:"rites and music" },
  "典籍":     { py:"diǎnjí",           zh:"古代的重要书籍",              en:"ancient classics / texts" },
  "六艺":     { py:"liù yì",           zh:"古代六种技能：礼、乐、射、御、书、数", en:"the “Six Arts” (rites, music, archery, charioteering, writing, maths)" },
  "请教":     { py:"qǐngjiào",         zh:"虚心向别人学习、问问题",       en:"to ask sb. for advice; to consult" },
  "罔":       { py:"wǎng",             zh:"迷惑、糊涂",                  en:"confused; at a loss" },
  "殆":       { py:"dài",              zh:"疑惑、危险",                  en:"in doubt; in peril" },
  "学而不厌": { py:"xué ér bù yàn",    zh:"学习永不满足",                en:"never tire of learning" },
  "座右铭":   { py:"zuòyòumíng",       zh:"用来勉励自己的话",            en:"a motto to live by" },
  "开创":     { py:"kāichuàng",        zh:"第一个创立",                  en:"to pioneer; to found" },
  "有教无类": { py:"yǒu jiào wú lèi",  zh:"不分贵贱贫富，人人都能受教育",  en:"education for all, regardless of background" },
  "贵贱":     { py:"guìjiàn",          zh:"地位高低",                    en:"high and low social status" },
  "贫富":     { py:"pínfù",            zh:"穷和富",                      en:"poor and rich" },
  "择其善者而从之，其不善者而改之": { py:"zé qí shàn zhě ér cóng zhī, qí bù shàn zhě ér gǎi zhī",
              zh:"学别人的长处，改自己的短处", en:"follow others' good points, correct your own faults" },
  "精英":     { py:"jīngyīng",         zh:"最优秀的人",                  en:"the elite; the best" },
  "谦逊":     { py:"qiānxùn",          zh:"谦虚、不骄傲",                en:"modest; humble" },
  "辩":       { py:"biàn",             zh:"争论、辩论",                  en:"to argue; to debate" },
  "评判":     { py:"píngpàn",          zh:"判断谁对谁错",                en:"to judge; to arbitrate" },
  "智慧":     { py:"zhìhuì",           zh:"聪明、有见识",                en:"wisdom" },
  "承认":     { py:"chéngrèn",         zh:"老实说出（不懂或做错）",       en:"to admit; to acknowledge" },
  "至圣先师": { py:"zhì shèng xiān shī",zh:"对孔子的最高尊称，“最伟大的老师”", en:"“the Greatest Sage and Teacher” (title for Confucius)" },
  "论语":     { py:"Lúnyǔ",            zh:"记录孔子言行的书",            en:"the Analects (record of Confucius's words)" },
  "经典":     { py:"jīngdiǎn",         zh:"长期流传的重要作品",          en:"a classic" },
  "名门望族": { py:"míngmén wàngzú",   zh:"有名有地位的大家族",          en:"a distinguished, noble family" },
  "公子哥":   { py:"gōngzǐgē",         zh:"有钱人家不做事的少爷",        en:"a rich, pampered young master" },
  "惨":       { py:"cǎn",              zh:"悲惨、可怜",                  en:"miserable; wretched" },
  "管仓库":   { py:"guǎn cāngkù",      zh:"看管仓库",                    en:"to look after a warehouse" },
  "喂牲口":   { py:"wèi shēngkou",     zh:"喂养家畜",                    en:"to feed livestock" },
  "文武双全": { py:"wén wǔ shuāng quán",zh:"文才和武艺都很好",           en:"skilled in both scholarship and martial arts" },
  "厌":       { py:"yàn",              zh:"满足；厌倦",                  en:"to be satisfied; to tire of" },
  "焉":       { py:"yān",              zh:"文言助词，“在其中”",           en:"(classical particle) therein" },
  "缺点":     { py:"quēdiǎn",          zh:"不好的地方",                  en:"shortcoming; fault" },
  "反省":     { py:"fǎnxǐng",          zh:"检查自己的错误",              en:"to reflect on oneself" },
  "贵族":     { py:"guìzú",            zh:"有地位的上层人",              en:"the nobility; aristocrat" },
  "特权":     { py:"tèquán",           zh:"特殊的权利",                  en:"privilege" },
  "尊敬":     { py:"zūnjìng",          zh:"敬重",                        en:"to respect" },
  "圣人":     { py:"shèngrén",         zh:"品德智慧最高的人",            en:"a sage" },
  "争论":     { py:"zhēnglùn",         zh:"各说各的、辩论",              en:"to argue; to dispute" },
  "竟然":     { py:"jìngrán",          zh:"出乎意料地",                  en:"unexpectedly; to one's surprise" },
  "丢脸":     { py:"diūliǎn",          zh:"没面子、失面子",              en:"to lose face; embarrassing" },
  "知":       { py:"zhì",              zh:"这里通“智”，指智慧",           en:"here = wisdom (same as 智)" },
  "不懂装懂": { py:"bù dǒng zhuāng dǒng",zh:"不懂却假装懂",              en:"to pretend to know what one doesn't" },
  "勤奋好学": { py:"qínfèn hào xué",   zh:"努力又爱学习",                en:"diligent and eager to learn" },
  "谦虚诚实": { py:"qiānxū chéngshí",  zh:"谦虚又诚实",                  en:"modest and honest" }
};
Object.keys(window.WORDS).forEach(function(w){ window.WORDS[w].audio = "audio/words/"+w+".mp3"; });
